#ifndef _HOTCALL_OFT_FUNCTIONS_
#define _HOTCALL_OFT_FUNCTIONS_

#define hotcall_ecall_myenclave_sample 0
#define hotcall_ecall_ofproto_init_tables 1
#define hotcall_ecall_oftable_set_readonly 2
#define hotcall_ecall_oftable_is_readonly 3
#define hotcall_ecall_cls_rule_init 4
#define hotcall_ecall_cr_rule_overlaps 5
#define hotcall_ecall_cls_rule_destroy 6
#define hotcall_ecall_cls_rule_hash 7
#define hotcall_ecall_cls_rule_equal 8
#define hotcall_ecall_oftable_classifier_replace 9
#define hotcall_ecall_oftable_get_flags 10
#define hotcall_ecall_oftable_cls_count 11
#define hotcall_ecall_is_eviction_fields_enabled 12
#define hotcall_ecall_evg_group_resize 13
#define hotcall_ecall_evg_add_rule 14
#define hotcall_ecall_evg_remove_rule 15
#define hotcall_ecall_cls_remove 16
#define hotcall_ecall_choose_rule_to_evict 17
#define hotcall_ecall_oftable_mflows 18
#define hotcall_ecall_choose_rule_to_evict_p 19
#define hotcall_ecall_minimatch_expand 20
#define hotcall_ecall_cr_priority 21
#define hotcall_ecall_oftable_cls_find_match_exactly 22
#define hotcall_ecall_collect_rules_loose_c 23
#define hotcall_ecall_collect_rules_loose_r 24
#define hotcall_ecall_collect_rules_strict_c 25
#define hotcall_ecall_collect_rules_strict_r 26
#define hotcall_ecall_oftable_enable_eviction 27
#define hotcall_ecall_oftable_disable_eviction 28
#define hotcall_ecall_oftable_enable_eviction_c 29
#define hotcall_ecall_oftable_enable_eviction_r 30
#define hotcall_ecall_oftable_mflows_set 31
#define hotcall_ecall_ofproto_destroy 32
#define hotcall_ecall_total_rules 33
#define hotcall_ecall_oftable_name 34
#define hotcall_ecall_collect_ofmonitor_util_c 35
#define hotcall_ecall_collect_ofmonitor_util_r 36
#define hotcall_ecall_cls_rule_is_loose_match 37
#define hotcall_ecall_flush_c 38
#define hotcall_ecall_flush_r 39
#define hotcall_ecall_flow_stats_c 40
#define hotcall_ecall_flow_stats_r 41
#define hotcall_ecall_oftable_cls_lookup 42
#define hotcall_ecall_cls_rule_priority 43
#define hotcall_ecall_dpif_destroy_c 44
#define hotcall_ecall_dpif_destroy_r 45
#define hotcall_ecall_cls_rule_format 46
#define hotcall_ecall_miniflow_expand 47
#define hotcall_ecall_rule_calculate_tag 48
//#define hotcall_ofproto_init_tables 49
#define hotcall_ecall_oftable_update_taggable 50
#define hotcall_ecall_oftable_is_other_table 51
#define hotcall_ecall_rule_calculate_tag_s 52
#define hotcall_ecall_oftable_hidden_check 53
#define hotcall_ecall_oftable_set_name 54
#define hotcall_ecall_minimask_get_vid_mask 55
#define hotcall_ecall_miniflow_get_vid 56
#define hotcall_ecall_ofproto_get_vlan_c 57
#define hotcall_ecall_ofproto_get_vlan_r 58

#define hotcall_ecall_oftable_get_cls_rules 59
#define hotcall_ecall_get_cls_rules_and_enable_eviction 60
#define hotcall_ecall_eviction_group_add_rules 61
#define hotcall_ecall_ofproto_get_vlan_usage 62
#define hotcall_ecall_ofproto_flush 63
#define hotcall_ecall_ofproto_evict 64
#define hotcall_ecall_add_flow 65
#define hotcall_ecall_collect_rules_loose 66
#define hotcall_ecall_collect_rules_strict 67
#define hotcall_ecall_delete_flows 68
#define hotcall_ecall_oftable_configure 69
#define hotcall_ecall_need_to_evict 70
#define hotcall_ecall_collect_rules_loose_stats_request 71
#define hotcall_ecall_ofproto_rule_send_removed 72
#define hotcall_ecall_oftable_remove_rules 73
#define hotcall_ecall_ofproto_evict_get_rest 74

#define hotcall_ecall_cls_rules_format 75
#define hotcall_ecall_minimatch_expand_and_get_priority 76
#define hotcall_ecall_miniflow_expand_and_tag 77

#define hotcall_ecall_set_evictable 78
#define hotcall_ecall_is_evictable 79
#define hotcall_ecall_restore_evictable 80
#define hotcall_ecall_backup_evictable 81
#define hotcall_ecall_rule_update_used 82
#define hotcall_ecall_backup_and_set_evictable 83

#define hotcall_ecall_ofproto_is_flow_deletion_pending 84
#define hotcall_ecall_modify_flows_loose 85
#define hotcall_ecall_modify_flows_strict 86
#define hotcall_ecall_delete_flows_loose 87
#define hotcall_ecall_configure_tables 88
#define hotcall_ecall_delete_flows_strict 89

#define hotcall_ecall_rule_from_cls_rule 90
#define hotcall_ecall_container_of 91
#define hotcall_ecall_offset_of 92

#define hotcall_ecall_offset_of_ret 93
#define hotcall_ecall_container_of_ret 94

#define hotcall_ecall_plus_one 95
#define hotcall_ecall_minus_one 96


#define hotcall_ecall_test 240
#define hotcall_ecall_async_test 241

#define hotcall_ecall_rule_eviction_priority 120


#endif
